/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiparisTakipRouteImport } from './routes/siparis-takip'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegistrationSuccessRouteImport } from './routes/registration-success'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MesafeliSatisSozlesmesiRouteImport } from './routes/mesafeli-satis-sozlesmesi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KisiselVerilerRouteImport } from './routes/kisisel-veriler'
import { Route as KargoVeTasimaRouteImport } from './routes/kargo-ve-tasima'
import { Route as KargoDegisimRouteImport } from './routes/kargo-degisim'
import { Route as IptalIadeKosullariRouteImport } from './routes/iptal-iade-kosullari'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as GizlilikPolitikasiRouteImport } from './routes/gizlilik-politikasi'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as DashboardAddressesRouteImport } from './routes/dashboard/addresses'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as ApiIyzicoCallbackRouteImport } from './routes/api/iyzico-callback'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminReturnsRouteImport } from './routes/admin/returns'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCampaignsRouteImport } from './routes/admin/campaigns'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard/orders/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as DashboardOrdersIdRouteImport } from './routes/dashboard/orders/$id'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiLocalUploadSplatRouteImport } from './routes/api/local-upload/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminProductsIdRouteImport } from './routes/admin/products/$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiparisTakipRoute = SiparisTakipRouteImport.update({
  id: '/siparis-takip',
  path: '/siparis-takip',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationSuccessRoute = RegistrationSuccessRouteImport.update({
  id: '/registration-success',
  path: '/registration-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MesafeliSatisSozlesmesiRoute = MesafeliSatisSozlesmesiRouteImport.update({
  id: '/mesafeli-satis-sozlesmesi',
  path: '/mesafeli-satis-sozlesmesi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KisiselVerilerRoute = KisiselVerilerRouteImport.update({
  id: '/kisisel-veriler',
  path: '/kisisel-veriler',
  getParentRoute: () => rootRouteImport,
} as any)
const KargoVeTasimaRoute = KargoVeTasimaRouteImport.update({
  id: '/kargo-ve-tasima',
  path: '/kargo-ve-tasima',
  getParentRoute: () => rootRouteImport,
} as any)
const KargoDegisimRoute = KargoDegisimRouteImport.update({
  id: '/kargo-degisim',
  path: '/kargo-degisim',
  getParentRoute: () => rootRouteImport,
} as any)
const IptalIadeKosullariRoute = IptalIadeKosullariRouteImport.update({
  id: '/iptal-iade-kosullari',
  path: '/iptal-iade-kosullari',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikPolitikasiRoute = GizlilikPolitikasiRouteImport.update({
  id: '/gizlilik-politikasi',
  path: '/gizlilik-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAddressesRoute = DashboardAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIyzicoCallbackRoute = ApiIyzicoCallbackRouteImport.update({
  id: '/api/iyzico-callback',
  path: '/api/iyzico-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardOrdersIdRoute = DashboardOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalUploadSplatRoute = ApiLocalUploadSplatRouteImport.update({
  id: '/api/local-upload/$',
  path: '/api/local-upload/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/iptal-iade-kosullari': typeof IptalIadeKosullariRoute
  '/kargo-degisim': typeof KargoDegisimRoute
  '/kargo-ve-tasima': typeof KargoVeTasimaRoute
  '/kisisel-veriler': typeof KisiselVerilerRoute
  '/login': typeof LoginRoute
  '/mesafeli-satis-sozlesmesi': typeof MesafeliSatisSozlesmesiRoute
  '/profile': typeof ProfileRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/siparis-takip': typeof SiparisTakipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/iyzico-callback': typeof ApiIyzicoCallbackRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/local-upload/$': typeof ApiLocalUploadSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/iptal-iade-kosullari': typeof IptalIadeKosullariRoute
  '/kargo-degisim': typeof KargoDegisimRoute
  '/kargo-ve-tasima': typeof KargoVeTasimaRoute
  '/kisisel-veriler': typeof KisiselVerilerRoute
  '/login': typeof LoginRoute
  '/mesafeli-satis-sozlesmesi': typeof MesafeliSatisSozlesmesiRoute
  '/profile': typeof ProfileRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/siparis-takip': typeof SiparisTakipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/iyzico-callback': typeof ApiIyzicoCallbackRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/local-upload/$': typeof ApiLocalUploadSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/iptal-iade-kosullari': typeof IptalIadeKosullariRoute
  '/kargo-degisim': typeof KargoDegisimRoute
  '/kargo-ve-tasima': typeof KargoVeTasimaRoute
  '/kisisel-veriler': typeof KisiselVerilerRoute
  '/login': typeof LoginRoute
  '/mesafeli-satis-sozlesmesi': typeof MesafeliSatisSozlesmesiRoute
  '/profile': typeof ProfileRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/siparis-takip': typeof SiparisTakipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/iyzico-callback': typeof ApiIyzicoCallbackRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/local-upload/$': typeof ApiLocalUploadSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/favorites'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/iletisim'
    | '/iptal-iade-kosullari'
    | '/kargo-degisim'
    | '/kargo-ve-tasima'
    | '/kisisel-veriler'
    | '/login'
    | '/mesafeli-satis-sozlesmesi'
    | '/profile'
    | '/registration-success'
    | '/settings'
    | '/signup'
    | '/siparis-takip'
    | '/sitemap.xml'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/settings'
    | '/api/iyzico-callback'
    | '/api/stripe-webhook'
    | '/checkout/success'
    | '/dashboard/addresses'
    | '/products/$slug'
    | '/admin/'
    | '/checkout/'
    | '/products/'
    | '/admin/products/$id'
    | '/api/auth/$'
    | '/api/local-upload/$'
    | '/api/rpc/$'
    | '/dashboard/orders/$id'
    | '/admin/products/'
    | '/dashboard/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/iletisim'
    | '/iptal-iade-kosullari'
    | '/kargo-degisim'
    | '/kargo-ve-tasima'
    | '/kisisel-veriler'
    | '/login'
    | '/mesafeli-satis-sozlesmesi'
    | '/profile'
    | '/registration-success'
    | '/settings'
    | '/signup'
    | '/siparis-takip'
    | '/sitemap.xml'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/settings'
    | '/api/iyzico-callback'
    | '/api/stripe-webhook'
    | '/checkout/success'
    | '/dashboard/addresses'
    | '/products/$slug'
    | '/admin'
    | '/checkout'
    | '/products'
    | '/admin/products/$id'
    | '/api/auth/$'
    | '/api/local-upload/$'
    | '/api/rpc/$'
    | '/dashboard/orders/$id'
    | '/admin/products'
    | '/dashboard/orders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/favorites'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/iletisim'
    | '/iptal-iade-kosullari'
    | '/kargo-degisim'
    | '/kargo-ve-tasima'
    | '/kisisel-veriler'
    | '/login'
    | '/mesafeli-satis-sozlesmesi'
    | '/profile'
    | '/registration-success'
    | '/settings'
    | '/signup'
    | '/siparis-takip'
    | '/sitemap.xml'
    | '/admin/campaigns'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/returns'
    | '/admin/reviews'
    | '/admin/settings'
    | '/api/iyzico-callback'
    | '/api/stripe-webhook'
    | '/checkout/success'
    | '/dashboard/addresses'
    | '/products/$slug'
    | '/admin/'
    | '/checkout/'
    | '/products/'
    | '/admin/products/$id'
    | '/api/auth/$'
    | '/api/local-upload/$'
    | '/api/rpc/$'
    | '/dashboard/orders/$id'
    | '/admin/products/'
    | '/dashboard/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  GizlilikPolitikasiRoute: typeof GizlilikPolitikasiRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  IptalIadeKosullariRoute: typeof IptalIadeKosullariRoute
  KargoDegisimRoute: typeof KargoDegisimRoute
  KargoVeTasimaRoute: typeof KargoVeTasimaRoute
  KisiselVerilerRoute: typeof KisiselVerilerRoute
  LoginRoute: typeof LoginRoute
  MesafeliSatisSozlesmesiRoute: typeof MesafeliSatisSozlesmesiRoute
  ProfileRoute: typeof ProfileRoute
  RegistrationSuccessRoute: typeof RegistrationSuccessRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SiparisTakipRoute: typeof SiparisTakipRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiIyzicoCallbackRoute: typeof ApiIyzicoCallbackRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLocalUploadSplatRoute: typeof ApiLocalUploadSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siparis-takip': {
      id: '/siparis-takip'
      path: '/siparis-takip'
      fullPath: '/siparis-takip'
      preLoaderRoute: typeof SiparisTakipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-success': {
      id: '/registration-success'
      path: '/registration-success'
      fullPath: '/registration-success'
      preLoaderRoute: typeof RegistrationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesafeli-satis-sozlesmesi': {
      id: '/mesafeli-satis-sozlesmesi'
      path: '/mesafeli-satis-sozlesmesi'
      fullPath: '/mesafeli-satis-sozlesmesi'
      preLoaderRoute: typeof MesafeliSatisSozlesmesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kisisel-veriler': {
      id: '/kisisel-veriler'
      path: '/kisisel-veriler'
      fullPath: '/kisisel-veriler'
      preLoaderRoute: typeof KisiselVerilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kargo-ve-tasima': {
      id: '/kargo-ve-tasima'
      path: '/kargo-ve-tasima'
      fullPath: '/kargo-ve-tasima'
      preLoaderRoute: typeof KargoVeTasimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kargo-degisim': {
      id: '/kargo-degisim'
      path: '/kargo-degisim'
      fullPath: '/kargo-degisim'
      preLoaderRoute: typeof KargoDegisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iptal-iade-kosullari': {
      id: '/iptal-iade-kosullari'
      path: '/iptal-iade-kosullari'
      fullPath: '/iptal-iade-kosullari'
      preLoaderRoute: typeof IptalIadeKosullariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik-politikasi': {
      id: '/gizlilik-politikasi'
      path: '/gizlilik-politikasi'
      fullPath: '/gizlilik-politikasi'
      preLoaderRoute: typeof GizlilikPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/addresses': {
      id: '/dashboard/addresses'
      path: '/addresses'
      fullPath: '/dashboard/addresses'
      preLoaderRoute: typeof DashboardAddressesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/iyzico-callback': {
      id: '/api/iyzico-callback'
      path: '/api/iyzico-callback'
      fullPath: '/api/iyzico-callback'
      preLoaderRoute: typeof ApiIyzicoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/orders/$id': {
      id: '/dashboard/orders/$id'
      path: '/orders/$id'
      fullPath: '/dashboard/orders/$id'
      preLoaderRoute: typeof DashboardOrdersIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-upload/$': {
      id: '/api/local-upload/$'
      path: '/api/local-upload/$'
      fullPath: '/api/local-upload/$'
      preLoaderRoute: typeof ApiLocalUploadSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAddressesRoute: typeof DashboardAddressesRoute
  DashboardOrdersIdRoute: typeof DashboardOrdersIdRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAddressesRoute: DashboardAddressesRoute,
  DashboardOrdersIdRoute: DashboardOrdersIdRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  GizlilikPolitikasiRoute: GizlilikPolitikasiRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  IptalIadeKosullariRoute: IptalIadeKosullariRoute,
  KargoDegisimRoute: KargoDegisimRoute,
  KargoVeTasimaRoute: KargoVeTasimaRoute,
  KisiselVerilerRoute: KisiselVerilerRoute,
  LoginRoute: LoginRoute,
  MesafeliSatisSozlesmesiRoute: MesafeliSatisSozlesmesiRoute,
  ProfileRoute: ProfileRoute,
  RegistrationSuccessRoute: RegistrationSuccessRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SiparisTakipRoute: SiparisTakipRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiIyzicoCallbackRoute: ApiIyzicoCallbackRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLocalUploadSplatRoute: ApiLocalUploadSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
